/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JTable;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ortu extends javax.swing.JFrame {

    /**
     * Creates new form ortu
     */
    DefaultTableModel model;

    public ortu() {
          initComponents();
    String[] judul = {"NIK", "Nama", "Nama Ayah", "Pekerjaan Ayah", "Gaji Ayah", "Nama Ibu", "Pekerjaan Ibu", "Gaji Ibu" };
    model = new DefaultTableModel(judul, 0);
    tdata.setModel(model);
    tampilkan();

    tdata.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tabelMouseClicked(evt);
        }
              private void tabelMouseClicked(MouseEvent evt) {
                  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
              }
          });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdata = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tnik = new javax.swing.JTextField();
        tpekerjaanayah = new javax.swing.JTextField();
        tgajiayah = new javax.swing.JTextField();
        tnamaibu = new javax.swing.JTextField();
        tpekerjaanibu = new javax.swing.JTextField();
        tgajiibu = new javax.swing.JTextField();
        tnamaayah = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        bsimpan = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        butama = new javax.swing.JButton();
        bbersihkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        tdata.setBackground(new java.awt.Color(51, 51, 51));
        tdata.setForeground(new java.awt.Color(255, 255, 255));
        tdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIK", "Nama", "Nama Ayah", "Pekerjaan Ayah", "Penghasilan Ayah", "Nama Ibu", "Pekerjaan Ibu", "Penghasilan Ibu"
            }
        ));
        jScrollPane1.setViewportView(tdata);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("Pendaftaran Siswa Baru");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Orang Tua");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIK Pendaftar");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Pendaftar");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Ayah");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pekerjaan Ayah");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Penghasilan Ayah ");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Penghasilan Ibu");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pekerjaan Ibu");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama Ibu");

        tnik.setBackground(new java.awt.Color(51, 51, 51));
        tnik.setForeground(new java.awt.Color(255, 255, 255));
        tnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnikActionPerformed(evt);
            }
        });

        tpekerjaanayah.setBackground(new java.awt.Color(51, 51, 51));
        tpekerjaanayah.setForeground(new java.awt.Color(255, 255, 255));
        tpekerjaanayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpekerjaanayahActionPerformed(evt);
            }
        });

        tgajiayah.setBackground(new java.awt.Color(51, 51, 51));
        tgajiayah.setForeground(new java.awt.Color(255, 255, 255));
        tgajiayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgajiayahActionPerformed(evt);
            }
        });

        tnamaibu.setBackground(new java.awt.Color(51, 51, 51));
        tnamaibu.setForeground(new java.awt.Color(255, 255, 255));
        tnamaibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaibuActionPerformed(evt);
            }
        });

        tpekerjaanibu.setBackground(new java.awt.Color(51, 51, 51));
        tpekerjaanibu.setForeground(new java.awt.Color(255, 255, 255));
        tpekerjaanibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpekerjaanibuActionPerformed(evt);
            }
        });

        tgajiibu.setBackground(new java.awt.Color(51, 51, 51));
        tgajiibu.setForeground(new java.awt.Color(255, 255, 255));
        tgajiibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgajiibuActionPerformed(evt);
            }
        });

        tnamaayah.setBackground(new java.awt.Color(51, 51, 51));
        tnamaayah.setForeground(new java.awt.Color(255, 255, 255));
        tnamaayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaayahActionPerformed(evt);
            }
        });

        tnama.setBackground(new java.awt.Color(51, 51, 51));
        tnama.setForeground(new java.awt.Color(255, 255, 255));
        tnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaActionPerformed(evt);
            }
        });

        bsimpan.setBackground(new java.awt.Color(153, 204, 255));
        bsimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bedit.setBackground(new java.awt.Color(153, 204, 255));
        bedit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bedit.setText("Edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        bhapus.setBackground(new java.awt.Color(153, 204, 255));
        bhapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bkeluar.setBackground(new java.awt.Color(51, 51, 51));
        bkeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bkeluar.setForeground(new java.awt.Color(255, 255, 255));
        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        butama.setBackground(new java.awt.Color(153, 204, 255));
        butama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        butama.setText("Halaman Utama");
        butama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butamaActionPerformed(evt);
            }
        });

        bbersihkan.setBackground(new java.awt.Color(153, 204, 255));
        bbersihkan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bbersihkan.setText("Bersihkan");
        bbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbersihkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(tnik, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tnama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tnamaayah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tpekerjaanayah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(236, 236, 236)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(48, 48, 48))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(76, 76, 76)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(59, 59, 59))
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tgajiayah, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(tnamaibu)
                    .addComponent(tpekerjaanibu)
                    .addComponent(tgajiibu))
                .addGap(136, 136, 136))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(bsimpan)
                .addGap(59, 59, 59)
                .addComponent(bedit)
                .addGap(71, 71, 71)
                .addComponent(bhapus)
                .addGap(71, 71, 71)
                .addComponent(bbersihkan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(butama)
                .addGap(55, 55, 55)
                .addComponent(bkeluar)
                .addGap(92, 92, 92))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(512, 512, 512)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(tgajiayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tnamaibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpekerjaanibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tnamaayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tgajiibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpekerjaanayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bhapus)
                    .addComponent(butama)
                    .addComponent(bkeluar)
                    .addComponent(bedit)
                    .addComponent(bsimpan)
                    .addComponent(bbersihkan))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butamaActionPerformed
    utama Formutama = new utama();
               Formutama.setVisible(true);
               dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_butamaActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
    int selectedRow = tdata.getSelectedRow();
    if (selectedRow != -1) {
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            // Ambil nilai NIK dari baris terpilih
            String nik = (String) tdata.getValueAt(selectedRow, 0);

            // Hapus baris terpilih dari tabel
            model.removeRow(selectedRow);

            // Hapus data dari database
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ppdb_", "root", "");
                String query = "DELETE FROM orangtua WHERE NIK=?";
                PreparedStatement pst = cn.prepareStatement(query);
                pst.setString(1, nik);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error menghapus data dari database: " + ex.getMessage());
                Logger.getLogger(ortu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus");
    }
    }//GEN-LAST:event_bhapusActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
         int selectedRow = tdata.getSelectedRow();
    if (selectedRow != -1) {
        String nik = (String) tdata.getValueAt(selectedRow, 0);

        // Ambil data dari inputan
        String nama = tnama.getText();
        String namaAyah = tnamaayah.getText();
        String pekerjaanAyah = tpekerjaanayah.getText();
        String gajiAyah = tgajiayah.getText();
        String namaIbu = tnamaibu.getText();
        String pekerjaanIbu = tpekerjaanibu.getText();
        String gajiIbu = tgajiibu.getText();

        // Update data di tabel GUI
        tdata.setValueAt(nik, selectedRow, 0);
        tdata.setValueAt(nama, selectedRow, 1);
        tdata.setValueAt(namaAyah, selectedRow, 2);
        tdata.setValueAt(pekerjaanAyah, selectedRow, 3);
        tdata.setValueAt(gajiAyah, selectedRow, 4);
        tdata.setValueAt(namaIbu, selectedRow, 5);
        tdata.setValueAt(pekerjaanIbu, selectedRow, 6);
        tdata.setValueAt(gajiIbu, selectedRow, 7);

        // Update data di database
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ppdb_", "root", "");
            String query = "UPDATE orangtua SET nama=?, namaayah=?, pekerjaanayah=?, gajiayah=?, namaibu=?, pekerjaanibu=?, gajiibu=? WHERE nik=?";
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, nama);
            pst.setString(2, namaAyah);
            pst.setString(3, pekerjaanAyah);
            pst.setString(4, gajiAyah);
            pst.setString(5, namaIbu);
            pst.setString(6, pekerjaanIbu);
            pst.setString(7, gajiIbu);
            pst.setString(8, nik);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error mengupdate data di database: " + ex.getMessage());
            Logger.getLogger(ortu.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan diupdate");
    }             
    }//GEN-LAST:event_beditActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
    String nik = tnik.getText();
    String nama = tnama.getText();
    String namaAyah = tnamaayah.getText();
    String pekerjaanAyah = tpekerjaanayah.getText();
    String gajiAyah = tgajiayah.getText();
    String namaIbu = tnamaibu.getText();
    String pekerjaanIbu = tpekerjaanibu.getText();
    String gajiIbu = tgajiibu.getText();

    // Tambahkan data ke tabel GUI
    String[] data = {nik, nama, namaAyah, pekerjaanAyah, gajiAyah, namaIbu, pekerjaanIbu, gajiIbu};
    model.addRow(data);

    // Simpan data ke database
    try {
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ppdb_", "root", "");
        String query = "INSERT INTO orangtua (nik, nama, namaayah, pekerjaanayah, gajiayah, namaibu, pekerjaanibu, gajiibu) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = cn.prepareStatement(query);
        pst.setString(1, nik);
        pst.setString(2, nama);
        pst.setString(3, namaAyah);
        pst.setString(4, pekerjaanAyah);
        pst.setString(5, gajiAyah);
        pst.setString(6, namaIbu);
        pst.setString(7, pekerjaanIbu);
        pst.setString(8, gajiIbu);
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error menyimpan data ke database: " + ex.getMessage());
        Logger.getLogger(ortu.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void tnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaActionPerformed

    private void tnamaayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaayahActionPerformed

    private void tgajiibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgajiibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgajiibuActionPerformed

    private void tpekerjaanibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpekerjaanibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpekerjaanibuActionPerformed

    private void tnamaibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaibuActionPerformed

    private void tgajiayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgajiayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgajiayahActionPerformed

    private void tpekerjaanayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpekerjaanayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpekerjaanayahActionPerformed

    private void tnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnikActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
            System.exit(0);}
            // Menampilkan konfirmasi yang menanyakan pengguna apakah ingin keluar dari aplikasi atau tidak 
               // TODO add your handling code here:
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbersihkanActionPerformed
        tnik.setText("");
        tnama.setText("");
        tnamaayah.setText("");
        tpekerjaanayah.setText("");
        tgajiayah.setText("");
        tnamaibu.setText("");
        tpekerjaanibu.setText("");
        tgajiibu.setText(""); 
        //membersihkan text yang ada di kolom pengisisan
// TODO add your handling code here:
    }//GEN-LAST:event_bbersihkanActionPerformed

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ortu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbersihkan;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton butama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tdata;
    private javax.swing.JTextField tgajiayah;
    private javax.swing.JTextField tgajiibu;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnamaayah;
    private javax.swing.JTextField tnamaibu;
    private javax.swing.JTextField tnik;
    private javax.swing.JTextField tpekerjaanayah;
    private javax.swing.JTextField tpekerjaanibu;
    // End of variables declaration//GEN-END:variables
    private void tampilkan() {
        int row = model.getRowCount();
        for (int a = row - 1; a >= 0; a--) {
            model.removeRow(a);
        }

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ppdb_", "root", "");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM orangtua");

            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8) };
                model.addRow(data);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Koneksi ke database gagal: " + ex.getMessage());
            Logger.getLogger(ortu.class.getName()).log(Level.SEVERE, null, ex);
        }
    


            // Initialize your components here
            // Example: jTextField1 = new javax.swing.JTextField();
         catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error initializing components: " + e.getMessage());
            Logger.getLogger(ortu.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    // Add other methods and components as needed
}