
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class utama extends javax.swing.JFrame {
    /**
     * Creates new form utama
     */
    public utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbortu = new javax.swing.JButton();
        tbsiswa = new javax.swing.JButton();
        tbkeluar = new javax.swing.JButton();
        tbtransaksi = new javax.swing.JButton();
        tbtabelortu = new javax.swing.JButton();
        tbtabeltransaksi = new javax.swing.JButton();
        tbtabelsiswa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Utama");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pendaftaran Siswa Baru");

        tbortu.setBackground(new java.awt.Color(153, 204, 255));
        tbortu.setText("Data Orang Tua");
        tbortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbortuActionPerformed(evt);
            }
        });

        tbsiswa.setBackground(new java.awt.Color(153, 204, 255));
        tbsiswa.setText("Data Siswa");
        tbsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbsiswaActionPerformed(evt);
            }
        });

        tbkeluar.setBackground(new java.awt.Color(153, 153, 153));
        tbkeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbkeluar.setText("Keluar");
        tbkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbkeluarActionPerformed(evt);
            }
        });

        tbtransaksi.setBackground(new java.awt.Color(153, 204, 255));
        tbtransaksi.setText("Data Transaksi");
        tbtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtransaksiActionPerformed(evt);
            }
        });

        tbtabelortu.setBackground(new java.awt.Color(153, 204, 255));
        tbtabelortu.setText("Laporan Data Orang tua");
        tbtabelortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtabelortuActionPerformed(evt);
            }
        });

        tbtabeltransaksi.setBackground(new java.awt.Color(153, 204, 255));
        tbtabeltransaksi.setText("Laporan Data Transaksi");
        tbtabeltransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtabeltransaksiActionPerformed(evt);
            }
        });

        tbtabelsiswa.setBackground(new java.awt.Color(153, 204, 255));
        tbtabelsiswa.setText("Laporan Data Siswa");
        tbtabelsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtabelsiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbortu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtabelortu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtabeltransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtabelsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(tbkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtabelsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtabelortu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbortu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbtabeltransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(tbkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbsiswaActionPerformed
    siswa Formsiswa = new siswa();
               Formsiswa.setVisible(true);
               dispose();    
               //berpindah ke halaman data siswa
// TODO add your handling code here:
    }//GEN-LAST:event_tbsiswaActionPerformed

    private void tbkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbkeluarActionPerformed
    int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
    if (konfirmasi == JOptionPane.YES_OPTION) {
    System.exit(0);}
        // Menampilkan konfirmasi yang menanyakan pengguna apakah ingin keluar dari aplikasi atau tidak
        // TODO add your handling code here:
    }//GEN-LAST:event_tbkeluarActionPerformed

    private void tbtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtransaksiActionPerformed
    transaksi Formtransaksi = new transaksi();
               Formtransaksi.setVisible(true);
               dispose();    
            //berpindah ke halaman data transaksi   
            // TODO add your handling code here:
    }//GEN-LAST:event_tbtransaksiActionPerformed

    private void tbortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbortuActionPerformed
    ortu Formortu = new ortu();
               Formortu.setVisible(true);
               dispose();        
               //berpindah ke halaman data orang tua
// TODO add your handling code here:
    }//GEN-LAST:event_tbortuActionPerformed

    private void tbtabelortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtabelortuActionPerformed
        tabelortu Formtabelortu = new tabelortu();
               Formtabelortu.setVisible(true);
               dispose();
               //berpindah ke halaman laporan data orang tua
// TODO add your handling code here:
    }//GEN-LAST:event_tbtabelortuActionPerformed

    private void tbtabeltransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtabeltransaksiActionPerformed
    tabeltransaksi Formtabeltransaksi = new tabeltransaksi();
               Formtabeltransaksi.setVisible(true);
               dispose();
               //berpindah ke halaman laporan data transaksi    
// TODO add your handling code here:
    }//GEN-LAST:event_tbtabeltransaksiActionPerformed

    private void tbtabelsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtabelsiswaActionPerformed
    tabelsiswa Formtabelsiswa = new tabelsiswa();
               Formtabelsiswa.setVisible(true);
               dispose();
               //berpindah ke halaman laporan data siswa    
// TODO add your handling code here:
    }//GEN-LAST:event_tbtabelsiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tbkeluar;
    private javax.swing.JButton tbortu;
    private javax.swing.JButton tbsiswa;
    private javax.swing.JButton tbtabelortu;
    private javax.swing.JButton tbtabelsiswa;
    private javax.swing.JButton tbtabeltransaksi;
    private javax.swing.JButton tbtransaksi;
    // End of variables declaration//GEN-END:variables
}
